[package]
name = "delve-shim-dap"
version = "0.2.0"
edition = "2024"
authors = ["Zed Team <hi@zed.dev>"]
license = "Apache-2.0"

[dependencies]
anyhow = "1"
debugserver-types = "0.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
